on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'master'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python action.py
      - name: Check for modified files # https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Publish to GitHub
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "MrOplus"
          git config --global user.email "MrOplus@yahoo.fr"
          git add .
          git commit -m "Update data"
          git push
